'use strict';
const $=id=>document.getElementById(id);
const escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateLabel=d=>new Date(d+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric'});
const timeLabel=t=>{const[h,m]=t.split(':').map(Number);return `${h%12||12}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'}`};
function validate(h){if(!h||!Array.isArray(h.events)||!Array.isArray(h.snacks)||h.snacks.length!==8||!h.snacks.every(x=>typeof x==='string')||!Array.isArray(h.updates))throw Error('Invalid team file');const date=d=>typeof d==='string'&&/^20\d\d-\d\d-\d\d$/.test(d)&&!isNaN(Date.parse(d))&&new Date(d).toISOString().slice(0,10)===d;const clock=t=>typeof t==='string'&&/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(t);if(!h.events.every(e=>date(e.date)&&['game','practice'].includes(e.kind)&&clock(e.start)&&clock(e.end)&&e.end>e.start&&typeof e.field==='string'&&typeof e.opponent==='string'&&typeof e.cancelled==='boolean')||!h.updates.every(u=>date(u.date)&&typeof u.title==='string'&&typeof u.body==='string'))throw Error('Invalid event or announcement');return h}
let current=null;
function renderNext(h){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date());const part=k=>parts.find(p=>p.type===k).value;const now=`${part('year')}-${part('month')}-${part('day')}T${part('hour')}:${part('minute')}`;const next=h.events.filter(e=>!e.cancelled&&e.date+'T'+e.end>=now).sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start))[0];$('next').innerHTML=next?`<div class="next-top"><span class="eyebrow">NEXT UP</span><span class="pill">${next.kind==='game'?'GAME DAY':'PRACTICE'}</span></div><p class="next-date">${dateLabel(next.date)}</p><h2>${next.kind==='game'?`Badgers <span>vs ${escapeHtml(next.opponent)}</span>`:'Team practice'}</h2><div class="next-meta"><span>${timeLabel(next.start)} – ${timeLabel(next.end)}</span><span>Hilltop Family YMCA · ${escapeHtml(next.field)}</span></div><a href="#schedule" class="next-link">Full team schedule <span aria-hidden="true">↗</span></a>`:'<span class="eyebrow">NEXT UP</span><h2>More soccer to come.</h2><p>No upcoming events are posted. Check coach updates for the latest.</p>'}
function render(h){renderNext(h);$('announcements').innerHTML=h.updates.length?h.updates.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(u=>`<article><time datetime="${u.date}">${dateLabel(u.date)}</time><h3>${escapeHtml(u.title)}</h3><p class="prewrap">${escapeHtml(u.body)}</p></article>`).join(''):'<div class="empty-update"><span class="empty-line"></span><h3>No announcements yet</h3><p>Practice reminders, game changes and team news will appear here.</p></div>';
$('events').innerHTML=h.events.slice().sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start)).map(e=>`<div class="event-row ${e.cancelled?'cancelled':''}"><div class="date-chip"><span>${new Date(e.date+'T12:00:00').toLocaleDateString('en-US',{month:'short'})}</span><strong>${Number(e.date.slice(-2))}</strong></div><div class="event-info"><span class="eyebrow">${new Date(e.date+'T12:00:00').toLocaleDateString('en-US',{weekday:'long'})} ${e.kind}${e.cancelled?' · CANCELLED':''}</span><h3>${e.kind==='game'?`Badgers vs ${escapeHtml(e.opponent)}`:'Team practice'}</h3><p>${timeLabel(e.start)} – ${timeLabel(e.end)}</p></div><span class="field">${escapeHtml(e.field)}</span></div>`).join('');
$('families').innerHTML=h.snacks.map((f,i)=>`<div class="snack-row ${f?'':'open'}"><span class="week">${String(i+1).padStart(2,'0')}<small>WEEK</small></span><div><strong>${escapeHtml(f||'Volunteer needed')}</strong>${f?'':'<span>Tell Coach Joe to claim this week.</span>'}</div>${f?'':'<span class="open-badge">OPEN</span>'}</div>`).join('');}
async function load(){try{const r=await fetch('./team.json',{cache:'no-store'});if(!r.ok)throw Error('Load failed');current=validate(await r.json());render(current);$('error').hidden=true;}catch{current=null;$('error').hidden=false;$('next').innerHTML='<span class="eyebrow">NEXT UP</span><h2>Schedule unavailable</h2><p>Please retry or check with Coach Joe.</p>';$('announcements').textContent='Updates are temporarily unavailable.';$('events').replaceChildren();$('families').replaceChildren();}}
$('retry').addEventListener('click',load);load();setInterval(()=>{if(current)renderNext(current)},60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load()});
